#!/bin/bash
# Conda 環境快速指令備忘錄

echo "=================================================="
echo "   Taiwan Analyst Signal Pipeline - 環境指南"
echo "=================================================="
echo ""
echo "📦 環境資訊："
echo "   名稱：tw-analyst"
echo "   Python：3.11.14"
echo "   位置：/tmp2/b12902115/conda/envs/tw-analyst"
echo ""
echo "=================================================="
echo "常用指令："
echo "=================================================="
echo ""
echo "🔹 激活環境："
echo "   conda activate tw-analyst"
echo ""
echo "🔹 檢查環境："
echo "   conda env list                  # 列出所有環境"
echo "   conda list                       # 查看已安裝套件"
echo "   which python                     # 確認 Python 路徑"
echo "   python --version                 # 查看 Python 版本"
echo ""
echo "🔹 退出環境："
echo "   conda deactivate"
echo ""
echo "🔹 刪除環境（謹慎使用）："
echo "   conda deactivate                 # 先退出"
echo "   conda env remove -n tw-analyst   # 刪除環境"
echo ""
echo "🔹 更新套件："
echo "   conda activate tw-analyst"
echo "   pip install --upgrade <package_name>"
echo ""
echo "🔹 匯出環境："
echo "   conda activate tw-analyst"
echo "   conda env export > environment.yml"
echo ""
echo "🔹 重建環境："
echo "   conda env create -f environment.yml"
echo ""
echo "=================================================="
echo "專案指令："
echo "=================================================="
echo ""
echo "🔹 進入專案："
echo "   cd /tmp2/b12902115/tw-analyst-signal-pipeline"
echo ""
echo "🔹 系統測試："
echo "   conda activate tw-analyst"
echo "   python3 scripts/test_system.py"
echo ""
echo "🔹 功能示範："
echo "   conda activate tw-analyst"
echo "   python3 scripts/demo.py"
echo ""
echo "🔹 處理影片："
echo "   conda activate tw-analyst"
echo "   python3 scripts/process_video.py <VIDEO_URL>"
echo ""
echo "🔹 查看日誌："
echo "   tail -f logs/pipeline.log"
echo ""
echo "=================================================="
echo "故障排除："
echo "=================================================="
echo ""
echo "❌ 'conda: command not found'"
echo "   解決： eval \"\$(conda shell.bash hook)\""
echo ""
echo "❌ 'No module named XXX'"
echo "   解決： conda activate tw-analyst 確認環境已激活"
echo "         pip list | grep <module_name> 檢查是否安裝"
echo ""
echo "❌ API Key 錯誤"
echo "   解決： cp .env.example .env"
echo "         nano .env  # 填入正確的 API keys"
echo ""
echo "=================================================="
echo "✅ 環境已準備完成！"
echo "=================================================="
echo ""
