analysts:
- channel: '@s178'
  name: 郭哲榮分析師-摩爾證券投顧
- channel: '@WE178'
  name: 鐘崑禎分析師_摩爾證券投顧
- channel: '@gp52000'
  name: 謝晨彥分析師-摩爾證券投顧
- channel: '@daren888'
  name: 陳昆仁分析師-摩爾證券投顧
- channel: '@gd1788'
  name: 何基鼎分析師-摩爾證券投顧
