#!/usr/bin/env python3
"""Keep only YouTube-relevant cookies in Netscape cookie file format."""

import argparse
from pathlib import Path

KEEP_COOKIE_NAMES = {
    "SID",
    "HSID",
    "SSID",
    "APISID",
    "SAPISID",
    "SIDCC",
    "LOGIN_INFO",
    "PREF",
    "SOCS",
    "VISITOR_INFO1_LIVE",
    "VISITOR_PRIVACY_METADATA",
    "YSC",
    "__Secure-1PAPISID",
    "__Secure-1PSID",
    "__Secure-1PSIDCC",
    "__Secure-1PSIDTS",
    "__Secure-3PAPISID",
    "__Secure-3PSID",
    "__Secure-3PSIDCC",
    "__Secure-3PSIDTS",
}

KEEP_DOMAIN_MARKERS = ("youtube.com", "google.com")


def should_keep(parts: list[str]) -> bool:
    if len(parts) < 7:
        return False
    domain = parts[0].strip().lower()
    name = parts[5].strip()
    return any(marker in domain for marker in KEEP_DOMAIN_MARKERS) and name in KEEP_COOKIE_NAMES


def clean_cookie_file(input_path: Path, output_path: Path) -> tuple[int, int]:
    lines = input_path.read_text(encoding="utf-8", errors="ignore").splitlines()

    header = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by yt-dlp.  Do not edit.",
        "",
    ]

    kept = []
    total_cookie_rows = 0
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        parts = line.split("\t")
        if len(parts) < 7:
            continue

        total_cookie_rows += 1
        if should_keep(parts):
            kept.append("\t".join(parts[:7]))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_text = "\n".join(header + kept) + "\n"
    output_path.write_text(output_text, encoding="utf-8")

    return total_cookie_rows, len(kept)


def main() -> int:
    parser = argparse.ArgumentParser(description="Clean yt-dlp cookies file")
    parser.add_argument("--input", default="local/cookies.txt")
    parser.add_argument("--output", default=None)
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output) if args.output else input_path

    if not input_path.exists():
        raise FileNotFoundError(f"Cookie file not found: {input_path}")

    total, kept = clean_cookie_file(input_path=input_path, output_path=output_path)
    print(f"[INFO] Cookie rows: total={total}, kept={kept}, removed={total - kept}")
    print(f"[INFO] Cleaned cookie file written to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
